version: "3"
services:
  mjpeg-proxy:
    container_name: node
    restart: unless-stopped
    image: ghcr.io/oxivanisher/node-mjpeg-proxy:master
    # build: .
    ports:
      - "8080:8080"
    volumes:
      - ./custom.js:/app/proxy.js:ro
